# Generated by Django 5.0.6 on 2024-05-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDePesquisa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_area', models.CharField(max_length=100)),
                ('nome_subarea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fomentador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fomento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verba_aprovada', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha_de_busca', models.CharField(max_length=255)),
                ('resultado', models.TextField()),
                ('id_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('area_de_atuacao', models.CharField(max_length=255)),
                ('lattes', models.CharField(max_length=255)),
                ('projetos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('participantes', models.CharField(max_length=255)),
                ('objetivos', models.CharField(max_length=255)),
                ('resultados', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('area_de_atuacao', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('desenvolvimento', models.TextField()),
                ('autores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetolab.pesquisador')),
            ],
        ),
    ]
