# Generated by Django 3.2.25 on 2024-06-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetolab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_pics/'),
        ),
    ]
